# Generated by Django 4.0 on 2022-06-30 13:24

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarshowroomCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('number', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'carshowroom_car',
            },
        ),
        migrations.CreateModel(
            name='CarshowroomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('balance', models.IntegerField(default=0)),
                ('car_characteristic', models.JSONField()),
            ],
            options={
                'db_table': 'carshowroom',
            },
        ),
    ]
