# Generated by Django 4.0 on 2022-07-12 21:39

import datetime
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarshowroomCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('number', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'carshowroom_car',
            },
        ),
        migrations.CreateModel(
            name='CarshowroomDiscountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_end', models.DateField(auto_created=datetime.date(2022, 7, 26))),
                ('time_start', models.DateField(auto_created=datetime.date(2022, 7, 12))),
                ('name', models.CharField(max_length=120)),
                ('percent', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CarshowroomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('balance', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('car_characteristic', models.JSONField()),
                ('client_discount', models.PositiveIntegerField(default=5)),
                ('number_of_prod', models.PositiveIntegerField(default=20)),
            ],
            options={
                'db_table': 'carshowroom',
            },
        ),
        migrations.CreateModel(
            name='SupplierPurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_purchases', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'supplier_purchase_history',
            },
        ),
    ]
