# Generated by Django 4.0 on 2022-07-06 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_carmodel_body_type_alter_carmodel_brand_and_more'),
        ('suppliers', '0007_alter_discountmodel_time_end_and_more'),
        ('carshowroom', '0004_alter_carshowroommodel_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_purchases', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carmodel')),
                ('carshowroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carshowroom.carshowroommodel')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.suppliermodel')),
            ],
            options={
                'db_table': 'supplier_purchase_history',
            },
        ),
    ]
