# Generated by Django 4.0 on 2022-07-11 09:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_carmodel_body_type_alter_carmodel_brand_and_more'),
        ('carshowroom', '0005_supplierpurchasehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshowroommodel',
            name='client_discount',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='carshowroommodel',
            name='number_of_prod',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.CreateModel(
            name='CarshowroomDiscountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_end', models.DateField(auto_created=datetime.date(2022, 7, 25))),
                ('time_start', models.DateField(auto_created=datetime.date(2022, 7, 11))),
                ('name', models.CharField(max_length=120)),
                ('percent', models.PositiveIntegerField(default=0)),
                ('car', models.ManyToManyField(to='core.CarModel')),
                ('carshowroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carshowroom.carshowroommodel')),
            ],
        ),
    ]
