version: '3.4'

services:
  whitesnakeproject:
    image: whitesnakeproject
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=$DATABASE_URL
      - EMAIL_HOST=$EMAIL_HOST
      - EMAIL_PORT=$EMAIL_PORT
      - EMAIL_HOST_USER=$EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
      - EMAIL_USE_TLS=$EMAIL_USE_TLS
      - EMAIL_USE_SSL=$EMAIL_USE_SSL
    depends_on:
      - db
      - redis
      - celery
      - celery_beat
      - pgadmin_serv
    env_file:
      - ./.env

  db:
    image: postgres:13-alpine
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    env_file:
      - ./.env

  redis:
    image: redis
    restart: always

  celery:
    restart: always
    build:
      context: .
    command:  ['celery', '-A', 'config', 'worker']
    volumes:
      - ./CarshowroomProject:/app
    environment:
      - DEBUG=1
      - DATABASE_URL=$DATABASE_URL
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    depends_on:
      - redis
    env_file:
      - ./.env

  celery_beat:
    build:
      context: ./
    command: ['celery', '-A', 'config', 'beat']
    volumes:
      - ./CarshowroomProject:/app
    environment:
      - DEBUG=1
      - DATABASE_URL=$DATABASE_URL
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    depends_on:
      - redis
    env_file:
      - ./.env

  pgadmin_serv:
    container_name: pgadmin_serv
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
    ports:
      - "5050:80"
    env_file:
      - ./.env

volumes:
  postgresql_data:
