# Generated by Django 4.0 on 2022-07-13 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carshowroom', '0001_initial'),
        ('core', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpurchasehistory',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carmodel'),
        ),
        migrations.AddField(
            model_name='supplierpurchasehistory',
            name='carshowroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carshowroom.carshowroommodel'),
        ),
        migrations.AddField(
            model_name='supplierpurchasehistory',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.suppliermodel'),
        ),
        migrations.AddField(
            model_name='carshowroommodel',
            name='car_list',
            field=models.ManyToManyField(through='carshowroom.CarshowroomCar', to='core.CarModel'),
        ),
        migrations.AddField(
            model_name='carshowroomdiscountmodel',
            name='car',
            field=models.ManyToManyField(to='core.CarModel'),
        ),
        migrations.AddField(
            model_name='carshowroomdiscountmodel',
            name='carshowroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carshowroom.carshowroommodel'),
        ),
        migrations.AddField(
            model_name='carshowroomcar',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carmodel'),
        ),
        migrations.AddField(
            model_name='carshowroomcar',
            name='carshowroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carshowroom.carshowroommodel'),
        ),
        migrations.AddField(
            model_name='carshowroomcar',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.suppliermodel'),
        ),
    ]
