# Generated by Django 4.0 on 2022-07-04 13:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='body_type',
            field=models.CharField(choices=[('sedan', 'SEDAN'), ('coupe', 'COUPE'), ('sport car', 'SPORT_CAR'), ('station vagon', 'STATION_VAGON'), ('hatchback', 'HATCHBACK'), ('convertible', 'CONVERTIBLE'), ('minivan', 'MINIVAN'), ('pickup truck', 'PICKUP_TRACK'), ('crossover', 'CROSSOVER')], max_length=30),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(choices=[('audi', 'Audi'), ('Hyundai', 'Hyundai'), ('Nissan', 'Nissan'), ('Suzuki', 'Suzuki'), ('BMW', 'BMW'), ('Kia', 'Kia'), ('Opel', 'Opel'), ('Toyota', 'Toyota')], max_length=30),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'petrol'), ('disel', 'disel'), ('CNG', 'CNG'), ('bio disel', 'bio_disel'), ('electric', 'electric')], default=core.models.FuelTypes['disel'], max_length=50),
        ),
    ]
