# Generated by Django 4.0 on 2022-06-30 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carshowroom', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('balance', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.baseuser')),
            ],
            options={
                'verbose_name': 'Customer',
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carmodel')),
                ('carshowroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carshowroom.carshowroommodel')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customermodel')),
            ],
            options={
                'db_table': 'purchase_history',
            },
        ),
        migrations.AddField(
            model_name='customermodel',
            name='purchase_history',
            field=models.ManyToManyField(through='customers.PurchaseHistory', to='carshowroom.CarshowroomModel'),
        ),
    ]
