# Generated by Django 4.0 on 2022-06-30 13:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_end', models.DateField(auto_created=datetime.date(2022, 7, 14))),
                ('time_start', models.DateField(auto_created=datetime.date(2022, 6, 30))),
                ('name', models.CharField(max_length=120)),
                ('percent', models.PositiveIntegerField(default=0)),
                ('car', models.ManyToManyField(to='core.CarModel')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carmodel')),
            ],
            options={
                'db_table': 'supplier_car',
            },
        ),
        migrations.CreateModel(
            name='SupplierModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('foundation_date', models.IntegerField(null=True)),
                ('client_discount', models.PositiveIntegerField(default=5)),
                ('number_of_prod', models.PositiveIntegerField(default=20)),
                ('car_list', models.ManyToManyField(through='suppliers.SupplierCar', to='core.CarModel')),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.discountmodel')),
            ],
            options={
                'verbose_name': 'Supplier',
                'db_table': 'suppliers',
            },
        ),
        migrations.AddField(
            model_name='suppliercar',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.suppliermodel'),
        ),
        migrations.AddField(
            model_name='discountmodel',
            name='supplier',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.suppliermodel'),
        ),
    ]
