# Generated by Django 4.0 on 2022-06-30 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliercar',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='suppliermodel',
            name='discount',
        ),
        migrations.AlterField(
            model_name='discountmodel',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.suppliermodel'),
        ),
    ]
