# Generated by Django 4.0 on 2022-07-04 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_remove_suppliercar_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliermodel',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='discountmodel',
            name='time_end',
            field=models.DateField(auto_created=datetime.date(2022, 7, 18)),
        ),
        migrations.AlterField(
            model_name='discountmodel',
            name='time_start',
            field=models.DateField(auto_created=datetime.date(2022, 7, 4)),
        ),
    ]
