# Generated by Django 4.0 on 2022-07-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_suppliermodel_balance_alter_discountmodel_time_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliermodel',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
