# Generated by Django 4.0 on 2022-07-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_alter_suppliermodel_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliermodel',
            name='balance',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
