# Generated by Django 4.0 on 2022-07-06 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_alter_suppliermodel_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountmodel',
            name='time_end',
            field=models.DateField(auto_created=datetime.date(2022, 7, 20)),
        ),
        migrations.AlterField(
            model_name='discountmodel',
            name='time_start',
            field=models.DateField(auto_created=datetime.date(2022, 7, 6)),
        ),
    ]
