# Generated by Django 4.0 on 2022-07-11 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_alter_discountmodel_time_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountmodel',
            name='time_end',
            field=models.DateField(auto_created=datetime.date(2022, 7, 25)),
        ),
        migrations.AlterField(
            model_name='discountmodel',
            name='time_start',
            field=models.DateField(auto_created=datetime.date(2022, 7, 11)),
        ),
    ]
